INSERT INTO [EC201101].[dbo].[UlazIzlaz]
           ([vID]
           ,[mID]
           ,[RAS]
           ,[Datum]
           ,[Knjizenje]
           ,[Broj]
           ,[ParID]
           ,[dtID]
           ,[Predznak]
           ,[Vreme]
           ,[Pristup]
           ,[DPO]
           ,[Valuta]
           ,[Klijent]
           ,[UserName]
           ,[Paritet]
           ,[Placanje]
           ,[Napomena]
           ,[Otprema]
           ,[Vozilo]
           ,[Vozac]
           ,[vIDStorno]
           ,[vIDNiv]
           ,[ParDokBroj]
           ,[Avans]
           ,[FaktSaRabatIznos]
           ,[Isporuka]
           ,[DatumDok]
           ,[Moneta]
           ,[Komercijalist]
           ,[vIDPrenos]
           ,[Naplata]
           ,[JCI]
           ,[KursnaLista]
           ,[Kurs]
           ,[PredBroj]
           ,[PostBroj]
           ,[Izdao])
   
SELECT UI.[vID]
      ,UI.[mID]
      ,UI.[RAS]
      ,'2011-01-01'
      ,'2011-01-01'
      ,UI.[Broj]
      ,UI.[ParID]
      ,UI.[dtID]--, dt.Naziv
      ,UI.[Predznak]
      ,UI.[Vreme]
      ,UI.[Pristup]
      ,UI.[DPO]
      ,UI.[Valuta]
      ,UI.[Klijent]
      ,UI.[UserName]
      ,UI.[Paritet]
      ,UI.[Placanje]
      ,UI.[Napomena]
      ,UI.[Otprema]
      ,UI.[Vozilo]
      ,UI.[Vozac]
      ,UI.[vIDStorno]
      ,UI.[vIDNiv]
      ,UI.[ParDokBroj]
      ,UI.[Avans]
      ,UI.[FaktSaRabatIznos]
      ,UI.[Isporuka]
      ,UI.[DatumDok]
      ,UI.[Moneta]
      ,UI.[Komercijalist]
      ,UI.[vIDPrenos]
      ,UI.[Naplata]
      ,UI.[JCI]
      ,UI.[KursnaLista]
      ,UI.[Kurs]
      ,UI.[PredBroj]
      ,UI.[PostBroj]
      ,UI.[Izdao]
  FROM [EC201001].[dbo].[UlazIzlaz] UI
 -- LEFT JOIN DokTip dt ON UI.dtID = dt.dtID
  where UI.RAS & 256 = 256 and UI.RAS & 1 <> 1 and ui.dtID in (30210,40210)
   --where UI.RAS & 256 = 256 and ui.dtID not in (30211, 30210,30500,40210,40211)







INSERT INTO [EC201101].[dbo].[UlazIzlazDetalj]
           ([vID]
           ,[RedBr]
           ,[ProID]
           ,[Kol]
           ,[Cena]
           ,[CSaPor]
           ,[Rabat]
           ,[Porez]
           ,[Tarifa]
           ,[Koef]
           ,[Realna]
           ,[Fakturna]
           ,[RabatFak]
           ,[Akciza]
           ,[Carina]
           ,[Naziv]
           ,[StaraCena]
           ,[StaraCenaSaPor]
           ,[StaraKol]
           ,[Trosak]
           ,[StvarnaKol]
           ,[CProdPrenos]
           ,[CProdPrenosBPor]
           ,[PDV]
           ,[ecBit]
           ,[PredznakParcijalneNiv]
           ,[PrenosRabat]
           ,[vPrenos]
           ,[MarzaPrenos]
           ,[Bruto]
           ,[Neto]
           ,[vJCI])
SELECT [vID]
      ,[RedBr]
      ,[ProID]
      ,[Kol]
      ,[Cena]
      ,[CSaPor]
      ,[Rabat]
      ,[Porez]
      ,[Tarifa]
      ,[Koef]
      ,[Realna]
      ,[Fakturna]
      ,[RabatFak]
      ,[Akciza]
      ,[Carina]
      ,[Naziv]
      ,[StaraCena]
      ,[StaraCenaSaPor]
      ,[StaraKol]
      ,[Trosak]
      ,[StvarnaKol]
      ,[CProdPrenos]
      ,[CProdPrenosBPor]
      ,[PDV]
      ,[ecBit]
      ,[PredznakParcijalneNiv]
      ,[PrenosRabat]
      ,[vPrenos]
      ,[MarzaPrenos]
      ,[Bruto]
      ,[Neto]
      ,[vJCI]
  FROM [EC201001].[dbo].[UlazIzlazDetalj]
where vID in (
  SELECT UI.[vID]
  FROM [EC201001].[dbo].[UlazIzlaz] UI
--  where UI.RAS & 256 = 256 and ui.dtID not in (30211, 30210,30500,40210,40211)
  where UI.RAS & 256 = 256 and UI.RAS & 1 <> 1 and ui.dtID in (30210,40210)
)
